services:

  dsw-server:
    image: dswbot/wizard-server:4.11
    platform: linux/amd64
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway

  dsw-client:
    image: dswbot/wizard-client:4.11
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      API_URL: http://localhost:3000/wizard-api

  dsw-docworker:
    image: dswbot/document-worker:4.11
    depends_on:
      - postgres
      - minio
      - dsw-server
    volumes:
      - ./application.yml:/app/config/application.yml:ro
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:16.4
    restart: always
    ports:
      - 127.0.0.1:15432:5432
    environment:
      POSTGRES_DB: wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2022-02-24T22-12-01Z
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    volumes:
     - s3-data:/data

  dsw-seed-maker:
    image: dswbot/dsw-seed-maker:develop
    ports:
      - 127.0.0.1:8000:8000
    env_file: seed_maker.env

volumes:
  db-data:
  s3-data:
