name: Code Style

on:
  push:

jobs:
  # Flake 8 for basic code style checks
  flake8:
    name: Flake 8
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install Flake8 (5.0.4)
      run: |
        python -m pip install --upgrade pip
        pip install flake8==5.0.4

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install package
      run: |
        pip install .

    - name: Lint with flake8
      run: |
        flake8 src/dsw_seed_maker --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/dsw_seed_maker --count --max-complexity=12 --max-line-length=130 --statistics

  # Typing checks with MyPy
  typing:
    name: Typing
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install MyPy (1.4.1)
      run: |
        python -m pip install --upgrade pip
        pip install mypy==1.4.1

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install packages
      run: |
        pip install .

    - name: Check typing with MyPy
      run: |
        mypy --install-types --ignore-missing-imports --check-untyped-defs --non-interactive src/dsw_seed_maker

  # Pylint linting
  pylint:
    name: Pylint
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Create build info
      run: |
        bash scripts/build-info.sh

    - name: Install PyLint (3.2.5)
      run: |
        python -m pip install --upgrade pip
        pip install pylint==3.2.5

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install packages
      run: |
        pip install .

    - name: Lint with PyLint
      run: |
        pylint --rcfile=.pylintrc.ini src/dsw_seed_maker